version: '3.9'
services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: time_tracker_api
    volumes:
      - data:/var/lib/postgresql/data
    restart: unless-stopped
  app:
    container_name: timetrackerapi
    ports:
      - "8080:8080"
    depends_on:
      - db
    build:
      dockerfile: .\Dockerfile
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/time_tracker_api
volumes:
  data: